//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webpage_survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string City { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public double Extroversion { get; set; }
        public double Agreeableness { get; set; }
        public double Conscientiousness { get; set; }
        public double Neuroticism { get; set; }
        public double Openness { get; set; }
        public string Status { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> timedate { get; set; }
        public string email { get; set; }
        public string nickname { get; set; }
    }
}
